application: infyrainbow
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /dbupdate
  script: dbmoduleput.app
- url: /images
  static_dir: images
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico
- url: /.*
  script: main.app
